spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowable?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 521037
flowable:
  #关闭定时任务job
  async-executor-activate: false
  